AWSTemplateFormatVersion: 2010-09-09
Description: Simple template for launching EC2 instance +SG with ssh enabled +IAM Role with deny rule. Made by Andrey Massalskiy (60641k)

Parameters:

  InstanceType:
    Description: The instance type to use for the EC2 instance. t2 and t3 available in different sizes. Default is t2.micro.
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.nano
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
      - t3.micro
      - t3.small
      - t3.medium
      - t3.large
      - t3.xlarge
      - t3.2xlarge

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: The name of the SSH key pair

  VPCID:
    Description: ID of the VPC.
    Type: AWS::EC2::VPC::Id

Resources:

IamRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument: 
        Version: 2012-10-17
        Statement:  
          - Effect: Allow
            Principal: 
              Service: 
                - ec2.amazonaws.com
            Action: 
              - sts:AssumeRole
      Description: AwsDeny role for Ec2Instance
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AWSDenyAll
      RoleName: SshServerRole
      Tags: 
        - Key: Name
          Value: SshServer

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      InstanceProfileName: ssh-server-instance-profile
      Roles: 
        - Ref: IamRole

  sshSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH connections
      SecurityGroupIngress:
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      VpcId:
        Ref: VPCID
      Tags:
        - Key: Name
          Value: SshServer

  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType:
        Ref: InstanceType
      ImageId: ami-00068cd7555f543d5
      SecurityGroupIds:
        - Ref: sshSG
      IamInstanceProfile: 
        Ref: InstanceProfile
      KeyName:
        Ref: KeyName
      Tags:
        - Key: Name
          Value: SshServer
