AWSTemplateFormatVersion: 2010-09-09
Description: simple template for launching EC2 instance +SG attached with ssh enabled by Andrey Massalskiy

Parameters:

  InstanceType:
    Description: The instance type to use for the EC2 instance. t2 and t3 available in different sizes. Default is t2.micro =)
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.nano
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
      - t3.micro
      - t3.small
      - t3.medium
      - t3.large
      - t3.xlarge
      - t3.2xlarge

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: The name of the SSH key pair

  VPCID:
    Description: ID of the VPC.
    Type: AWS::EC2::VPC::Id

Resources:

  sshSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH connections
      SecurityGroupIngress:
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      VpcId:
        Ref: VPCID
      Tags:
        - Key: Name
          Value: ssh-sg

  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType:
        Ref: InstanceType
      ImageId: ami-00dc79254d0461090
      SecurityGroupIds:
        - Ref: sshSG
      KeyName:
        Ref: KeyName
      Tags:
        - Key: Name
          Value: ssh-server
