AWSTemplateFormatVersion: 2010-09-09
Description: AutoScaling for 1 ec2 instance with SSH access enabled. by Andrey Massalskiy

Parameters:

  InstanceType:
    Description: The instance type to use for the EC2 instance. t2 and t3 available in different sizes. Default is t2.micro =)
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.nano
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
      - t3.micro
      - t3.small
      - t3.medium
      - t3.large
      - t3.xlarge
      - t3.2xlarge

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: The name of the SSH key pair

  VPCID:
    Description: ID of the VPC.
    Type: AWS::EC2::VPC::Id

  SubnetID:
    Description: ID of the subnet.
    Type: List<AWS::EC2::Subnet::Id>

Resources:

  sshSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH connections
      SecurityGroupIngress:
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      VpcId:
        Ref: VPCID
      Tags:
        - Key: Name
          Value: ssh-sg

  AutoScalingGroup:
      Type: AWS::AutoScaling::AutoScalingGroup
      Properties:
        AutoScalingGroupName: SSH Server Autoscaling Group
        Cooldown: 120
        DesiredCapacity: 1
        LaunchConfigurationName: 
          Ref: SshServerLaunchConfiguration 
        MaxSize: 1
        MinSize: 1
        Tags:
          - Key: Name
            Value: SSH Server ASG
            PropagateAtLaunch: 'true'
        VPCZoneIdentifier:
          Ref: SubnetID

  SshServerLaunchConfiguration: 
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties: 
      KeyName: 
        Ref: KeyName
      ImageId: ami-00dc79254d0461090
      SecurityGroups: 
        - Ref: sshSG
      InstanceType: 
        Ref: InstanceType



